// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: tempconv/v1/tempconv.proto

package tempconv_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TempConv_CelsiusToFahrenheit_FullMethodName = "/tempconv.v1.TempConv/CelsiusToFahrenheit"
	TempConv_FahrenheitToCelsius_FullMethodName = "/tempconv.v1.TempConv/FahrenheitToCelsius"
)

// TempConvClient is the client API for TempConv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TempConv converts between Celsius and Fahrenheit.
type TempConvClient interface {
	CelsiusToFahrenheit(ctx context.Context, in *Value, opts ...grpc.CallOption) (*Value, error)
	FahrenheitToCelsius(ctx context.Context, in *Value, opts ...grpc.CallOption) (*Value, error)
}

type tempConvClient struct {
	cc grpc.ClientConnInterface
}

func NewTempConvClient(cc grpc.ClientConnInterface) TempConvClient {
	return &tempConvClient{cc}
}

func (c *tempConvClient) CelsiusToFahrenheit(ctx context.Context, in *Value, opts ...grpc.CallOption) (*Value, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Value)
	err := c.cc.Invoke(ctx, TempConv_CelsiusToFahrenheit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tempConvClient) FahrenheitToCelsius(ctx context.Context, in *Value, opts ...grpc.CallOption) (*Value, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Value)
	err := c.cc.Invoke(ctx, TempConv_FahrenheitToCelsius_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TempConvServer is the server API for TempConv service.
// All implementations must embed UnimplementedTempConvServer
// for forward compatibility.
//
// TempConv converts between Celsius and Fahrenheit.
type TempConvServer interface {
	CelsiusToFahrenheit(context.Context, *Value) (*Value, error)
	FahrenheitToCelsius(context.Context, *Value) (*Value, error)
	mustEmbedUnimplementedTempConvServer()
}

// UnimplementedTempConvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTempConvServer struct{}

func (UnimplementedTempConvServer) CelsiusToFahrenheit(context.Context, *Value) (*Value, error) {
	return nil, status.Error(codes.Unimplemented, "method CelsiusToFahrenheit not implemented")
}
func (UnimplementedTempConvServer) FahrenheitToCelsius(context.Context, *Value) (*Value, error) {
	return nil, status.Error(codes.Unimplemented, "method FahrenheitToCelsius not implemented")
}
func (UnimplementedTempConvServer) mustEmbedUnimplementedTempConvServer() {}
func (UnimplementedTempConvServer) testEmbeddedByValue()                  {}

// UnsafeTempConvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TempConvServer will
// result in compilation errors.
type UnsafeTempConvServer interface {
	mustEmbedUnimplementedTempConvServer()
}

func RegisterTempConvServer(s grpc.ServiceRegistrar, srv TempConvServer) {
	// If the following call panics, it indicates UnimplementedTempConvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TempConv_ServiceDesc, srv)
}

func _TempConv_CelsiusToFahrenheit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TempConvServer).CelsiusToFahrenheit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TempConv_CelsiusToFahrenheit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TempConvServer).CelsiusToFahrenheit(ctx, req.(*Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _TempConv_FahrenheitToCelsius_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TempConvServer).FahrenheitToCelsius(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TempConv_FahrenheitToCelsius_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TempConvServer).FahrenheitToCelsius(ctx, req.(*Value))
	}
	return interceptor(ctx, in, info, handler)
}

// TempConv_ServiceDesc is the grpc.ServiceDesc for TempConv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TempConv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tempconv.v1.TempConv",
	HandlerType: (*TempConvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CelsiusToFahrenheit",
			Handler:    _TempConv_CelsiusToFahrenheit_Handler,
		},
		{
			MethodName: "FahrenheitToCelsius",
			Handler:    _TempConv_FahrenheitToCelsius_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tempconv/v1/tempconv.proto",
}
