// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: tempconv/v1/tempconv.proto

package tempconv_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Value holds a single numeric value (temperature).
type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_tempconv_v1_tempconv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_tempconv_v1_tempconv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_tempconv_v1_tempconv_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_tempconv_v1_tempconv_proto protoreflect.FileDescriptor

const file_tempconv_v1_tempconv_proto_rawDesc = "" +
	"\n" +
	"\x1atempconv/v1/tempconv.proto\x12\vtempconv.v1\"\x1d\n" +
	"\x05Value\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value2\x88\x01\n" +
	"\bTempConv\x12=\n" +
	"\x13CelsiusToFahrenheit\x12\x12.tempconv.v1.Value\x1a\x12.tempconv.v1.Value\x12=\n" +
	"\x13FahrenheitToCelsius\x12\x12.tempconv.v1.Value\x1a\x12.tempconv.v1.ValueBAZ?github.com/tempconv/backend/internal/pb/tempconv/v1;tempconv_v1b\x06proto3"

var (
	file_tempconv_v1_tempconv_proto_rawDescOnce sync.Once
	file_tempconv_v1_tempconv_proto_rawDescData []byte
)

func file_tempconv_v1_tempconv_proto_rawDescGZIP() []byte {
	file_tempconv_v1_tempconv_proto_rawDescOnce.Do(func() {
		file_tempconv_v1_tempconv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tempconv_v1_tempconv_proto_rawDesc), len(file_tempconv_v1_tempconv_proto_rawDesc)))
	})
	return file_tempconv_v1_tempconv_proto_rawDescData
}

var file_tempconv_v1_tempconv_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tempconv_v1_tempconv_proto_goTypes = []any{
	(*Value)(nil), // 0: tempconv.v1.Value
}
var file_tempconv_v1_tempconv_proto_depIdxs = []int32{
	0, // 0: tempconv.v1.TempConv.CelsiusToFahrenheit:input_type -> tempconv.v1.Value
	0, // 1: tempconv.v1.TempConv.FahrenheitToCelsius:input_type -> tempconv.v1.Value
	0, // 2: tempconv.v1.TempConv.CelsiusToFahrenheit:output_type -> tempconv.v1.Value
	0, // 3: tempconv.v1.TempConv.FahrenheitToCelsius:output_type -> tempconv.v1.Value
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tempconv_v1_tempconv_proto_init() }
func file_tempconv_v1_tempconv_proto_init() {
	if File_tempconv_v1_tempconv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tempconv_v1_tempconv_proto_rawDesc), len(file_tempconv_v1_tempconv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tempconv_v1_tempconv_proto_goTypes,
		DependencyIndexes: file_tempconv_v1_tempconv_proto_depIdxs,
		MessageInfos:      file_tempconv_v1_tempconv_proto_msgTypes,
	}.Build()
	File_tempconv_v1_tempconv_proto = out.File
	file_tempconv_v1_tempconv_proto_goTypes = nil
	file_tempconv_v1_tempconv_proto_depIdxs = nil
}
