// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/tempconv.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CelsiusToFahrenheitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CelsiusToFahrenheitRequest) Reset() {
	*x = CelsiusToFahrenheitRequest{}
	mi := &file_api_tempconv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CelsiusToFahrenheitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CelsiusToFahrenheitRequest) ProtoMessage() {}

func (x *CelsiusToFahrenheitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tempconv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CelsiusToFahrenheitRequest.ProtoReflect.Descriptor instead.
func (*CelsiusToFahrenheitRequest) Descriptor() ([]byte, []int) {
	return file_api_tempconv_proto_rawDescGZIP(), []int{0}
}

func (x *CelsiusToFahrenheitRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type CelsiusToFahrenheitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CelsiusToFahrenheitResponse) Reset() {
	*x = CelsiusToFahrenheitResponse{}
	mi := &file_api_tempconv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CelsiusToFahrenheitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CelsiusToFahrenheitResponse) ProtoMessage() {}

func (x *CelsiusToFahrenheitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tempconv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CelsiusToFahrenheitResponse.ProtoReflect.Descriptor instead.
func (*CelsiusToFahrenheitResponse) Descriptor() ([]byte, []int) {
	return file_api_tempconv_proto_rawDescGZIP(), []int{1}
}

func (x *CelsiusToFahrenheitResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type FahrenheitToCelsiusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FahrenheitToCelsiusRequest) Reset() {
	*x = FahrenheitToCelsiusRequest{}
	mi := &file_api_tempconv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FahrenheitToCelsiusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FahrenheitToCelsiusRequest) ProtoMessage() {}

func (x *FahrenheitToCelsiusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tempconv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FahrenheitToCelsiusRequest.ProtoReflect.Descriptor instead.
func (*FahrenheitToCelsiusRequest) Descriptor() ([]byte, []int) {
	return file_api_tempconv_proto_rawDescGZIP(), []int{2}
}

func (x *FahrenheitToCelsiusRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type FahrenheitToCelsiusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FahrenheitToCelsiusResponse) Reset() {
	*x = FahrenheitToCelsiusResponse{}
	mi := &file_api_tempconv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FahrenheitToCelsiusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FahrenheitToCelsiusResponse) ProtoMessage() {}

func (x *FahrenheitToCelsiusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tempconv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FahrenheitToCelsiusResponse.ProtoReflect.Descriptor instead.
func (*FahrenheitToCelsiusResponse) Descriptor() ([]byte, []int) {
	return file_api_tempconv_proto_rawDescGZIP(), []int{3}
}

func (x *FahrenheitToCelsiusResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_api_tempconv_proto protoreflect.FileDescriptor

const file_api_tempconv_proto_rawDesc = "" +
	"\n" +
	"\x12api/tempconv.proto\x12\btempconv\"2\n" +
	"\x1aCelsiusToFahrenheitRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"3\n" +
	"\x1bCelsiusToFahrenheitResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"2\n" +
	"\x1aFahrenheitToCelsiusRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"3\n" +
	"\x1bFahrenheitToCelsiusResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value2\xd9\x01\n" +
	"\x0fTempConvService\x12b\n" +
	"\x13CelsiusToFahrenheit\x12$.tempconv.CelsiusToFahrenheitRequest\x1a%.tempconv.CelsiusToFahrenheitResponse\x12b\n" +
	"\x13FahrenheitToCelsius\x12$.tempconv.FahrenheitToCelsiusRequest\x1a%.tempconv.FahrenheitToCelsiusResponseB\x0eZ\ftempconv/apib\x06proto3"

var (
	file_api_tempconv_proto_rawDescOnce sync.Once
	file_api_tempconv_proto_rawDescData []byte
)

func file_api_tempconv_proto_rawDescGZIP() []byte {
	file_api_tempconv_proto_rawDescOnce.Do(func() {
		file_api_tempconv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tempconv_proto_rawDesc), len(file_api_tempconv_proto_rawDesc)))
	})
	return file_api_tempconv_proto_rawDescData
}

var file_api_tempconv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_tempconv_proto_goTypes = []any{
	(*CelsiusToFahrenheitRequest)(nil),  // 0: tempconv.CelsiusToFahrenheitRequest
	(*CelsiusToFahrenheitResponse)(nil), // 1: tempconv.CelsiusToFahrenheitResponse
	(*FahrenheitToCelsiusRequest)(nil),  // 2: tempconv.FahrenheitToCelsiusRequest
	(*FahrenheitToCelsiusResponse)(nil), // 3: tempconv.FahrenheitToCelsiusResponse
}
var file_api_tempconv_proto_depIdxs = []int32{
	0, // 0: tempconv.TempConvService.CelsiusToFahrenheit:input_type -> tempconv.CelsiusToFahrenheitRequest
	2, // 1: tempconv.TempConvService.FahrenheitToCelsius:input_type -> tempconv.FahrenheitToCelsiusRequest
	1, // 2: tempconv.TempConvService.CelsiusToFahrenheit:output_type -> tempconv.CelsiusToFahrenheitResponse
	3, // 3: tempconv.TempConvService.FahrenheitToCelsius:output_type -> tempconv.FahrenheitToCelsiusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_tempconv_proto_init() }
func file_api_tempconv_proto_init() {
	if File_api_tempconv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tempconv_proto_rawDesc), len(file_api_tempconv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tempconv_proto_goTypes,
		DependencyIndexes: file_api_tempconv_proto_depIdxs,
		MessageInfos:      file_api_tempconv_proto_msgTypes,
	}.Build()
	File_api_tempconv_proto = out.File
	file_api_tempconv_proto_goTypes = nil
	file_api_tempconv_proto_depIdxs = nil
}
